name: tst-proxies-dpl-output-proxy
defaults:
control: 
  mode: "fairmq"
wants: 
  cpu: 0.15
  memory: 128
bind: 
  - name: downstream
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: 1
command:
  shell: true
  value: >-
    source /etc/profile.d/modules.sh && MODULEPATH={{ modulepath }} module load O2 QualityControl Control-OCCPlugin &&
    cat {{ dpl_config }} | o2-dpl-output-proxy
  user: "{{ user }}"
  arguments:
    - "-b"
    - "--monitoring-backend"
    - "{{ monitoring_qc_url }}"
    - "--session"
    - "default"
    - "--id"
    - "'dpl-output-proxy'"
    - "--shm-monitor"
    - "'false'"
    - "--log-color"
    - "'false'"
    - "--aod-memory-rate-limit"
    - "'0'"
    - "--aod-writer-json"
    - "''"
    - "--aod-writer-keep"
    - "''"
    - "--aod-writer-ntfmerge"
    - "-1"
    - "--aod-writer-resfile"
    - "''"
    - "--aod-writer-resmode"
    - "'RECREATE'"
    - "--channel-prefix"
    - "''"
    - "--clone"
    - "''"
    - "--dataspec"
    - "'A:TST/RAWDATA;dd:FLP/DISTSUBTIMEFRAME/0'"
    - "--default-port"
    - "'4200'"
    - "--default-transport"
    - "'shmem'"
    - "--fairmq-ipc-prefix"
    - "'/tmp/pkonopka'"
    - "--fairmq-rate-logging"
    - "'0'"
    - "--fairmq-recv-buffer-size"
    - "'1000'"
    - "--fairmq-send-buffer-size"
    - "'1000'"
    - "--forwarding-destination"
    - "'file'"
    - "--forwarding-policy"
    - "'dangling'"
    - "--output-proxy-address"
    - "'0.0.0.0'"
    - "--output-proxy-method"
    - "'bind'"
    - "--pipeline"
    - "''"
    - "--proxy-name"
    - "'dpl-output-proxy'"
    - "--readers"
    - "'1'"
    - "--severity"
    - "'info'"
    - "--shm-mlock-segment"
    - "'false'"
    - "--shm-segment-id"
    - "'0'"
    - "--shm-segment-size"
    - "'2000000000'"
    - "--shm-throw-bad-alloc"
    - "'true'"
    - "--shm-zero-segment"
    - "'false'"
    - "--stacktrace-on-signal"
    - "'all'"
    - "--workflow-suffix"
    - "''"
    - "--driver-client-backend"
    - "'ws://0.0.0.0:25886'"
